# Generated by Django 4.2.1 on 2023-06-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecart_application', '0003_alter_cart_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_current',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
