# Generated by Django 4.2.1 on 2023-06-09 08:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_application', '0005_alter_cart_quantity_alter_cart_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
